version: 2
registries:
  toptal-github:
    type: "git"
    url: "https://github.com"
    username: "x-access-token"
    password: "${{secrets.DEPENDABOT_GITHUB_TOKEN}}"

updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: "monthly"
    pull-request-branch-name:
      separator: "-"
    labels:
      - "no-jira"
      - "ruby"
      - "dependencies"
      - "WIP"
      - "DevX"
    reviewers:
      - "toptal/devx"
    registries:
      - toptal-github
    insecure-external-code-execution: allow
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: '*'
        update-types: [
          'version-update:semver-patch'
        ]
    groups:
      development-dependencies-group:
        dependency-type: development
        update-types:
          - "minor"
        exclude-patterns:
        - "rubocop*"
      production-dependencies-group:
        dependency-type: production
        update-types:
          - "minor"
      rubocop:
        patterns:
        - "rubocop*"
        update-types:
          - "major"
          - "minor"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    pull-request-branch-name:
      separator: "-"
    labels:
      - "no-jira"
      - "dependencies"
      - "gha"
      - "WIP"
      - "DevX"
    reviewers:
      - "toptal/devx"
    open-pull-requests-limit: 10
