require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  Include:
    - '**/*.rb'
    - '**/Gemfile'
    - '**/Rakefile'
  Exclude:
    - 'vendor/bundle/**/*'
    - 'log/**/*'
    - 'spec/fixtures/**/*'
  DisplayCopNames: true
  TargetRubyVersion: 2.6
  TargetRailsVersion: 5.1
  NewCops: enable

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

Gemspec/DevelopmentDependencies:
  Enabled: false

Naming/FileName:
  Exclude:
    - 'lib/rubocop-granite.rb'

Style/FrozenStringLiteralComment:
  Enabled: false
